name: CI

on:
  workflow_dispatch:
  push:
    branches: '*'
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    name: "ci 🔍"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: build
        name: Build
        uses: ./.github/actions/build
    outputs:
      artifact-name: ${{ steps.build.outputs.artifact-name }}
